version: '3.9'

services:
  api:
    image: eshop-api
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 5000:80
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=reallyStrongPwd123
    ports:
      - 1433:1433
    networks:
      - mynetwork

  web:
    build: ../FE/khoaht3-eshop
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
